# DATABASE (PUBLIC CONNECTION - since different project)
spring.datasource.url=jdbc:mysql://switchyard.proxy.rlwy.net:13861/railway
spring.datasource.username=root
spring.datasource.password=pZVCnWWKRhnvCweilsSHGCXMTrBEauly

# SERVER
server.port=${PORT:5454}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# FRONTEND
frontend.url=${FRONTEND_URL:https://subtle-gumdrop-648ce7.netlify.app}

# BREVO EMAIL API
brevo.api.key=${BREVO_API_KEY}
brevo.api.url=https://api.brevo.com/v3/smtp/email

# MACHINE LEARNING API
ml.service.url=http://localhost:5001