# DATABASE (Neon PostgreSQL)
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://ep-still-tooth-anyja8qx.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DATABASE_USERNAME:neondb_owner}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# SERVER
server.port=${PORT:5454}

# JPA (PostgreSQL configuration)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# FRONTEND
frontend.url=${FRONTEND_URL:https://sastaabazaar.shop}

# BREVO EMAIL API
brevo.api.key=${BREVO_API_KEY}
brevo.api.url=https://api.brevo.com/v3/smtp/email

# MACHINE LEARNING API
ml.service.url=https://sastabazzarrfinal-production-724e.up.railway.app